# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

target 'cultureapp' do
  # Set OpenSSL Version, to mitigate an issue with react-native-quick-crypto and OpenSSL 3
  # https://github.com/margelo/react-native-quick-crypto/issues/189
  pod "OpenSSL-Universal", "1.1.1100"
  # React Native Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  if %r{^0$}i.match ENV['NO_FLIPPER']
    flipper_configuration = FlipperConfiguration.enabled
  else
    flipper_configuration = FlipperConfiguration.disabled
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_configuration,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'cultureappTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
