def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

if %r{^0$}i.match ENV['NO_FLIPPER']
  # https://github.com/invertase/react-native-firebase/issues/6425#issuecomment-1527949355
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  $RNFirebaseAsStaticFramework = true
else
  use_frameworks! :linkage => :static
end

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

target 'cultureapp' do
  # Set OpenSSL Version, to mitigate an issue with react-native-quick-crypto and OpenSSL 3
  # https://github.com/margelo/react-native-quick-crypto/issues/189
  pod "OpenSSL-Universal", "1.1.1100"

  setup_permissions(['LocationAccuracy', 'LocationAlways', 'LocationWhenInUse', 'Notifications'])

  config = use_native_modules!

  if %r{^0$}i.match ENV['NO_FLIPPER']
    flipper_configuration = FlipperConfiguration.enabled
  else
    flipper_configuration = FlipperConfiguration.disabled
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_configuration,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'cultureappTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
