fastlane_version '2.211.0'

platform :ios do

  before_all do
    setup_ci
    sh("node --version")
    sh("npm -g ls --depth=0")
  end
  
  desc "Build project (Community)"
  lane :build do
      ENV["RCT_NO_LAUNCH_PACKAGER"] = "1"
      sh("echo 'DEV_MENU='true'' >> '../.env'")
      sh("echo 'AA2_DEVELOPER_MODE='true'' >> '../.env'")

      build_ios_app(
          export_method: "ad-hoc",
          configuration: "AdHoc",
          workspace: "./ios/cultureapp.xcworkspace",
          skip_codesigning: true,
          skip_package_ipa: true
      )
  end
end

desc "Add line with token to the SAP Artifactory"
lane :add_token_to_npmrc do
  sh(
    command: "echo '//'#{ENV["SAP_ARTIFACTORY_URL"]}'/:always-auth=true' >> '../.npmrc'",
    log: false
  )
  sh(
    command: "echo '//'#{ENV["SAP_ARTIFACTORY_URL"]}'/:_authToken=${SAP_ARTIFACTORY_TOKEN}' >> '../.npmrc'",
    log: false
  )
  sh(
    command: "echo '@sap:registry=https://'#{ENV["SAP_ARTIFACTORY_URL"]}'/' >> '../.npmrc'",
    log: false
  )
end
